
name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rspec:
    name: Rspec on Ruby ${{ matrix.ruby_version }} and libvips ${{ matrix.libvips_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ['2.3', '2.4', '2.5']
        libvips_version: ['8.6.5', '8.7.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby_version }}-${{matrix.libvips_version}}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ruby_version }}-${{matrix.libvips_version}}-gems-
    - uses: actions/cache@v2
      with:
        path: ~/vips
        key: ${{ runner.os }}-${{ matrix.ruby_version }}-${{matrix.libvips_version}}-vips-${{ hashFiles('**/install-vips.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ruby_version }}-${{matrix.libvips_version}}-vips-

    - name: Setup Deps Package
      run: |
        apt-get install -y libexpat1-dev gettext liblcms2-dev \
        libmagickwand-dev libopenexr-dev libcfitsio-dev libgif-dev \
        libgs-dev libgsf-1-dev libmatio-dev libopenslide-dev liborc-0.4-dev \
        libpango1.0-dev libpoppler-glib-dev librsvg2-dev \
        libwebp-dev libfftw3-dev libglib2.0-dev tesseract-ocr \
        tesseract-ocr-chi-sim imagemagick
    - name: Setup Libvips
      run: |
        export LIBVIPS_VERSION=${{matrix.libvips_version}}
        bash install-vips.sh --without-python
    - name: Bundle
      run: |
        export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
        export PATH=$HOME/vips/bin:$PATH
        export LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
        export PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
        bundle config path vendor/bundle
        bundle install
    - name: Rspec
      run: bundle exec rspec